#!/usr/bin/env python
# Author: Saurav Pathak

from distutils.core import setup, Extension
import numpy as np

module_gen3fit = Extension('bopy.cgen3fit.gen3fit',
        define_macros = [('MAJOR_VERSION', '0'),
        ('MINOR_VERSION', '7')],
        include_dirs = ['/usr/local/include', np.get_include()],
        libraries = ['stdc++', 'gsl', 'gslcblas', 'fftw3'],
        depends = ['src/bopy/cgen3fit/gen3fit/cgen3fit.h',
                   'src/bopy/cgen3fit/gen3fit/fftfit.h',
                   'src/bopy/cgen3fit/gen3fit/clinfit.h'],
        library_dirs = ['/usr/local/lib'],
        sources = ['src/bopy/cgen3fit/gen3fit/cgen3fit.cc', 
                   'src/bopy/cgen3fit/gen3fit/fftfit.cc', 
                   'src/bopy/cgen3fit/gen3fit/clinfit.cc', 
                   'src/bopy/cgen3fit/gen3fit/gen3fit.cc']) 

setup(name='bopy',
        version='3.7',
        description='Biomedical Optics Utilities',
        author='Saurav Pathak',
        author_email='saurav@sas.upenn.edu',
        package_dir = {'': 'src'},
        ext_modules = [module_gen3fit],
        packages=['bopy', 
                  'bopy.io', 
                  'bopy.utils', 
                  'bopy.gen3fit', 
                  'bopy.viewer', 
                  'bopy.cgen3fit', 
                  'bopy.do', 
                  'bopy.lbs', 
                  'bopy.gen3pp', 
                  'bopy.spectra',
                  'bopy.breastshape',
                  'bopy.toast'],
        package_data={'bopy.spectra': ['data/*']},
        requires=['numpy', 
                  'pyfits', 
                  'scipy', 
                  'statsmodels', 
                  'traits', 
                  'traitsui', 
                  'rpy2', 
                  'matplotlib'],
        scripts=['bin/fitsinfo.py', 
                 'bin/bpview2d.py', 
                 'bin/bpview3d.py', 
                 'bin/bpview2d-xsection.py', 
                 'bin/gen3-breastoutline.py',
                 'bin/gen3-npy2mat.py',
                 'bin/gen3-slabfit.py', 
                 'bin/gen3-slabfit2.py',            # masks already made
                 'bin/gen3-slabfitms.py',            # masks already made
                 'bin/gen3-slabfit-mp.py', 
                 'bin/gen3-fit.py', 
                 'bin/gen3-fit2.py', 
                 'bin/gen3-fit3.py', 
                 'bin/gen3-fit4.py', 
                 'bin/gen3-fit5.py', 
                 'bin/gen3-lsfit.py', 
                 'bin/gen3-tsfit.py', 
                 'bin/gen3-lsanalysis.py', 
                 'bin/gen3-linfit.py', 
                 'bin/gen3-fit-old.py', 
                 'bin/gen3-calib.py', 
                 'bin/gen3-maskspo.py',
                 'bin/gen3-rocalib.py', 
                 'bin/gen3-polygon.py', 
                 'bin/gen3-points.py', 
                 'bin/gen3-pomaxrow.py',
                 'bin/gen3-pomincol.py',
                 'bin/gen3-poregion.py',
                 'bin/gen3-sample.py', 
                 'bin/gen3-showppdata.py',
                 'bin/gen3-bshape.py', 
                 'bin/gen3-homog.py', 
                 'bin/gen3-hottestpixel.py',
                 'bin/gen3-readlbs.py', 
                 'bin/gen3-togauss.py', 
                 'bin/gen3-viewallsources.py',
                 'bin/gen3-viewallsources-mask.py',
                 'bin/gen3-viewmasked.py',
                 'bin/gen3-allsource-masked.py',
                 'bin/gen3-compareview-masked.py',
                 'bin/gen3-compareviewallsource-masked.py',
                 'bin/gen3-compare-mean-allsource-masked.py',
                 'bin/gen3-compare-mean-allsource-masked-srccalib.py',
                 'bin/gen3-compare-each-source-masked.py',
                 'bin/gen3-correctbyonesource.py',
                 'bin/gen3-compareviewallsource-masked2.py',
                 'bin/gen3-compareviewallsource-masked-fast.py',
                 'bin/gen3-phasetestallsource.py',
                 'bin/gen3-phasenormalization-masked.py',
                 'bin/gen3-phasenormalization-loessed-masked.py',
                 'bin/gen3-checkphi-masked.py',
                 'bin/gen3-checkmasks.py',
                 'bin/gen3-checkdata.py',
                 'bin/fframeviewer.py', 
                 'bin/create-srccalibrate.py',
                 'bin/create-pickoff.py',
                 'bin/create_genmask2_masks.py',
                 'bin/create_maxpixels.py',
                 'bin/corr-all.py',
                 'bin/make-poly.py',
                 'bin/nef2mesh.py',
                 'bin/gen3-phaseunwrap.py',
                 'bin/gen3-toastdata.py',
                 'bin/pixviewer.py', 
                 'bin/gen3-init.py',
                 'bin/breasttanktop-mesh.py',
                 'bin/msh2inoutbreast.py',
                 'bin/breastvalues.py',
                 'bin/run-makemesh.sh',
                 'bin/run-cosfit2-init.sh',
                 'bin/run-cosfit2-srcfit.sh',
                 'bin/run-cosfit2-calibfit.sh',
                 'bin/run-cosfit2-pickofffit.sh',
                 'bin/run-setparams.sh',
                 'bin/run-setparams-nocorr.sh',
                 'bin/run-process.sh',
                 'bin/run-process-nocorr.sh',
                 'bin/run-toastdata-config.sh',
                 'bin/run-toastdata-config-nocorr.sh',
                 'bin/run-toastdata.sh',
                 'bin/run-toastdata-nocorr.sh',
                 'bin/run-breastprocess.sh'],
     )
