#ifndef _GEN3FIT_H_
#define _GEN3FIT_H_
#ifdef __cplusplus
extern "C" {
#endif
int getAPhiDC(const double* data,
            const unsigned int* axes,
            const double del_t,
            const double freq,
            const unsigned int nOfData,
            const double absErr,
            const double relErr,
            const unsigned int maxIter,
            double* A,
            double* phi,
            double* DC,
            unsigned long int* iters,
            long int* Status,
            double* delDC,
            double* delA,
            double* delPhi,
            double* chi2ByDOF);
            //double* initA,
            //double* initPhi,
            //double* initDC); 

int getAPhiDC2(const double* data,
            const unsigned int* axes,
            const double del_t,
            const double freq,
            const double phi_init,          // Note this, absent in getAPhiDC()
            const unsigned int nOfData,
            const double absErr,
            const double relErr,
            const unsigned int maxIter,
            double* A,
            double* phi,
            double* DC,
            unsigned long int* iters,
            long int* Status,
            double* delDC,
            double* delA,
            double* delPhi,
            double* chi2ByDOF,
            double* pcts,
            double* rse,
            double* nrse); 

int getPixelAPhiDC2(const double* data,
            const unsigned int* axes,
            const unsigned long int r,
            const unsigned long int c,
            const double del_t,
            const double freq,
            const double phi_init,
            const unsigned int nOfData,
            const double absErr,
            const double relErr,
            const unsigned int maxIter,
            double& A,
            double& phi,
            double& DC,
            unsigned long int& iters,
            long int& Status,
            double& delDC,
            double& delA,
            double& delPhi,
            double& chi2ByDOF,
            double& pcts,
            double& rse,
            double& nrse,
            double& ssr);

int getPixelAPhiDCTr(const double* data,
            const unsigned int* axes,
            const unsigned long int row,
            const unsigned long int col,
            const double del_t,
            const double freq,
            const double phi_init,
            const unsigned int nOfData,
            const double absErr,
            const double relErr,
            const unsigned int maxIter,
            double& A,
            double& phi,
            double& DC,
            double& alpha,
            unsigned long int& iters,
            long int& Status,
            double& delDC,
            double& delA,
            double& delPhi,
            double& delAlpha,
            double& chi2ByDOF,
            double& pcts,
            double& rse,
            double& nrse,
            double& ssr);

#ifdef __cplusplus
}
#endif
#endif
